language: node_js
before_install:
	- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
	- npm install -g npm@latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
node_js:
  - 0.12
notifications:
  email: false